-- I CREATED ALL COLUMNS AT THE BEGINNING BUT I'LL SHOW HOW TO ADD COLUMNS IN add.sql

-- CREATE TABLE Houses (
--     id SERIAL PRIMARY KEY,
--     name VARCHAR(30),
--     address VARCHAR(100),
--     city VARCHAR(100),
--     state VARCHAR(2),
--     zip INTEGER,
--     img TEXT,
--     mortgage DECIMAL,
--     rent DECIMAL
-- )